### ISSUE TITLE
Navigationsleiste Einträge

### ISSUE THREAD

**Issue by HSoeren** [se-ws22-ihnn/ihnn#13]
Die Einträge in der Navigationsleiste sollten, bis auf das Haupt "IHNN" rechtsbündig sein.
siehe: `src/Components/Header.tsx:35`

@JannikHoefener welche Elemente braucht die Seite?

**Comment by JannikHoefener** [comment]
about us und frage einreichen (per popup)
Gruppe erstellen ist quasi auf der ersten- / startsseite

**Comment by HSoeren** [comment]
Ich würde das Problem als erledigt betrachten, in der Zwischenzeit hat sich vieles an der Navleiste geändert, Logo und Einreichen ist links-, Info und ThemeSelector (#15, #24) rechtsbündig.


<img width="870" alt="navbar" src="https://user-images.githubusercontent.com/25493517/209467589-1c2079a8-4686-4d0a-abbf-176375b42e1d.png">
