### ISSUE TITLE
AboutIHNN Component fertig bis auf Bild und Text soll inline sein 

### ISSUE THREAD

**Issue by JannikHoefener** [se-ws22-ihnn/ihnn#16]
einiges versucht verschachtlung von Boxen wobei die mutter box display inline hat) ... alles versuche bislang erfolg los

**Comment by JannikHoefener** [comment]
eine lösung wurde mit stack gefunden ... jz gehts nur noch ums design box größer ? text nicht so nah am rand?

**Comment by JannikHoefener** [comment]
evtl noch text anpassen

**Comment by HSoeren** [comment]
sieht sehr fertig aus
