### ISSUE TITLE
Player & Groups

### ISSUE THREAD

**Issue by HSoeren** [se-ws22-ihnn/ihnn#18]

**Comment by HSoeren** [comment]
![image](https://user-images.githubusercontent.com/25493517/205756420-2a2d3b31-a69c-4d64-8a1a-a7b3a40f3756.png)

**Comment by HSoeren** [comment]
![image](https://user-images.githubusercontent.com/25493517/205756483-61c44c18-fb79-41b7-a17a-f90c78a89f1f.png)

**Comment by HSoeren** [comment]
kann das hier zu? @JannikHoefener

**Comment by JannikHoefener** [comment]
da #23 nicht mehr umgesetzt wird ist dieses issue done
