### ISSUE TITLE
ThemeBuilder

### ISSUE THREAD

**Issue by HSoeren** [se-ws22-ihnn/ihnn#24]
https://bareynol.github.io/mui-theme-creator/

für standard Theme

**Comment by HSoeren** [comment]
Theme richtig hinterlegt, in `Components/Themes/light.ts`, nach einem Umbau der `index.tsx` und `app.tsx`.

Wenn wir nun ein weiteres Theme haben könnte man die `ThemeController.tsx` #15 erweitern und zB so die jeweils auswählen:
`<ThemeProvider theme={isLight ? lightTheme : darkTheme}>`

**Comment by JannikHoefener** [comment]
@Hyper1701 **erinnerung**: wie ist hier der stand? wenn erledigt, dann issue schließen mit kurzen kommentar!

**Comment by Hyper1701** [comment]
Beide Themes wurden erstellt und funktionieren theoretisch auch. Sie müssen nur noch mit dem Theme changer slider eingebunden werden.
