### ISSUE TITLE
Bei abstimmung slider farbig mit label

### ISSUE THREAD

**Issue by JannikHoefener** [se-ws22-ihnn/ihnn#26]
wenn keine abstimmung erfolgt ist default = habe noch nicht (oder in grau???)

Farblich den slider färben siehe bild 
Müsste mit if statement und useState gehen der mit setColor("red")

**Comment by JannikHoefener** [comment]
[](url)
![2022-12-09 13_08_53-Window](https://user-images.githubusercontent.com/82703032/206700075-f1495fff-dd4b-4830-a8de-9a842c65290d.png)

**Comment by HSoeren** [comment]
ist das noch relevant? wir haben ja jetzt buttons..

**Comment by HSoeren** [comment]
Während der Abstimmung hat jeder Spieler einfach zwei Schaltflächen / Buttons zur Auswahl, die sich nach Betätigung deaktivieren.
<img width="427" alt="Voting während einer Frage" src="https://user-images.githubusercontent.com/25493517/209467687-f9cc0ced-4442-429e-afbb-97088e0025e5.png">

In der Auswertung wird dann durch die Zahl der Votes neben der Option das Ergebnis visualisiert.
<img width="427" alt="Auswertung der Votes" src="https://user-images.githubusercontent.com/25493517/209467663-3f0d0773-3713-4351-a11d-8ed21a50073d.png">
