### ISSUE TITLE
wenn spiel beendet wird wird eine allgemeine "Score" Übersicht gegeben 

### ISSUE THREAD

**Issue by JannikHoefener** [se-ws22-ihnn/ihnn#27]

**Comment by JannikHoefener** [comment]
Component steht

**Comment by JannikHoefener** [comment]
Styling fehlt hier

**Comment by JannikHoefener** [comment]
@HSoeren wir müssen uns hier um .. kümmern
1. Gespielte Runden Counter damit am Ende sichlich ist qie viele runden man fragen bekommen hat
2. Anzeige der i did & i didnt counter hinter den Icons immoment noch null

**Comment by HSoeren** [comment]
sollte sich erledigt haben. Die gespielten runden werden jetzt angezeigt und dazu auch die menge an votes:
<img width="719" alt="State 3: Ende" src="https://user-images.githubusercontent.com/25493517/209467548-ce9d9378-7d83-411e-bdfd-da70fadae263.png">
