### ISSUE TITLE
handle newQuestion and Groupvoting

### ISSUE THREAD

**Issue by JannikHoefener** [se-ws22-ihnn/ihnn#30]
funktionalität um eine neue Frage zu erhalten steht bereits:
**Ansatz:**
- Aktuell werden Fragen noch von einer useState Liste of Type Question mit 3 default Fragen zur verfügung gestellt.
- man könnte diese liste später aus der fragen datenbank in random reinfolge befüllen lassen
- es gibt eine roundcounter variable, diese wird auch als index genutzt um durch die liste zu iterieren
- es müssen zwei componenten zusammen getan werden damit diese ihre werte teilen können
- - Aufbau der ganzen Komponente dann mit Grid
- hier sollte viel testing betrieben werden

**aktueller Bug:** wenn liste leer bzw durch gelaufen wurde, erscheint der browser weiß => ansatz mit while < list.lenght oder so

**Comment by HSoeren** [comment]
> **aktueller Bug:** wenn liste leer bzw durch gelaufen wurde, erscheint der browser weiß => ansatz mit while < list.lenght oder so

Jedes mal, wenn die Frage aus der Liste entnommen wurde, checken lassen, ob danach noch was kommt.
Falls Ja: heißt der Knopf "Nächste Frage"
Falls Nein: heißt der Knopf "Runde beenden"

**Comment by HSoeren** [comment]
> * man könnte diese liste später aus der fragen datenbank in random reinfolge befüllen lassen
> * es gibt eine roundcounter variable, diese wird auch als index genutzt um durch die liste zu iterieren

Also verstehe ich richtig? Liste aus der DB holen, randomisieren, Liste fürs Spiel ablegen?

**Comment by HSoeren** [comment]
newQuestion siehe #14

**Comment by JannikHoefener** [comment]
kann geschlossen werden, weitere Funktionalität folgt über issue #41
