### ISSUE TITLE
finaleScore (nach spiel beenden) + Chart

### ISSUE THREAD

**Issue by JannikHoefener** [se-ws22-ihnn/ihnn#32]

**Comment by JannikHoefener** [comment]
jetzt nicht mehr als Card / Popup sonder als "normale Komponente"

**Comment by JannikHoefener** [comment]
@Hyper1701 styling fehlt
@HSoeren habe ein Grid angelegt damit links möglicherweise dein Chart auftauchen kann

**Comment by HSoeren** [comment]
https://www.npmjs.com/package/react-minimal-pie-chart wäre ideal. quick and easy.

```typescript
import { PieChart } from 'react-minimal-pie-chart';

/* dev data for diagram */
const dataMock = [
    { title: 'Yes', value: 10, color: 'green' },
    { title: 'No', value: 15, color: 'red' },
];

const defaultLabelStyle = {
    fontSize: '5px',
    fontFamily: 'sans-serif',
};

---

<PieChart
    data={dataMock}
    label={({ dataEntry }) => dataEntry.value}
    labelStyle={{
        ...defaultLabelStyle,
    }}
/>
<PieChart
    data={dataMock}
    label={({ dataEntry }) => dataEntry.value}
    labelStyle={(index) => ({
        fill: dataMock[index].color,
        fontSize: '5px',
        fontFamily: 'sans-serif',
    })}
    radius={42}
    labelPosition={112}
/>
<PieChart
    data={dataMock}
    lineWidth={20}
    paddingAngle={18}
    rounded
    label={({ dataEntry }) => dataEntry.value}
    labelStyle={(index) => ({
        fill: dataMock[index].color,
        fontSize: '5px',
        fontFamily: 'sans-serif',
    })}
    labelPosition={60}
/>
```

**Comment by HSoeren** [comment]
![image](https://user-images.githubusercontent.com/25493517/209488560-cca634cc-e54b-4c53-8966-4358bf826e4d.png)

**Comment by HSoeren** [comment]
![image](https://user-images.githubusercontent.com/25493517/209696188-934bb511-335a-47a8-b1c3-9fb47ffe8a78.png)

Derzeit sind die Daten für das Diagramm in `src\Components\GroupScore.tsx` in `voteData` enthalten. Dies müsste noch auf die echten Daten umgebaut werden @JannikHoefener

**Comment by Hyper1701** [comment]
@HSoeren Ist das schon adaptierbar oder nur ein Bild? Ich finde das dritte design sieht auch super interessant aus, gute wahl.

**Comment by JannikHoefener** [comment]
const { group } = React.useContext(GroupContext);
    const allIDid = group.map((currentPlayer) => (currentPlayer.iDidCounter)).reduce((currentValue, perItem)=>{currentValue += perItem; return currentValue},0);
    const allIDidNot = group.map((currentPlayer) => (currentPlayer.iDidNotCounter)).reduce((currentValue, perItem)=>{currentValue += perItem; return currentValue},0);

const voteData = [
    { title: 'Yes', value: allIDid, color: '#3a883d' },
    { title: 'No', value: allIDidNot, color: '#dd3a2e' },
];

**Comment by JannikHoefener** [comment]
commit folgt

**Comment by JannikHoefener** [comment]
![image](https://user-images.githubusercontent.com/82703032/210065296-4d1119fc-7f24-4d21-8975-57eb5f251d28.png)
