### ISSUE TITLE
nach finaleScore zur Startseite bringen ... was muss zurück gesetzt werden

### ISSUE THREAD

**Issue by JannikHoefener** [se-ws22-ihnn/ihnn#34]
Gruppe leeren?
Liste zurücksetzen?

**Comment by HSoeren** [comment]
Gruppe nicht leeren, Liste leeren, die Votes löschen

**Comment by JannikHoefener** [comment]
`const handleGameReset = () => {
        // 1. State erhöhen
        increaseState();
        
        // 2. Score der Gruppe zurück setzen
        // group.map((currentPlayer)=>{currentPlayer.iDidCounter = 0,currentPlayer.iDidNotCounter = 0}); //<== eslint mag das nicht
        group.map((currentPlayer)=>{return currentPlayer.iDidCounter = 0}); 
        group.map((currentPlayer)=>{return currentPlayer.iDidNotCounter = 0});
        
        // 3. Roundcounter zurücksetzen
        setRoundCounter(1);
        
        // 4. Fragenkathalog durchmischen
        //DEBUG: console.log("alte Liste:", questionList);
        const shuffledArray = questionList.sort((a, b) => 0.5 - Math.random());
        setQuestionList([...shuffledArray]);
        //DEBUG: console.log("neue Liste:", questionList);
    }`
