### ISSUE TITLE
State change Buttons styling 

### ISSUE THREAD

**Issue by JannikHoefener** [se-ws22-ihnn/ihnn#35]
eig nur margin ... passend zum Grid?

**Comment by HSoeren** [comment]
betrifft ggf auch #19

**Comment by JannikHoefener** [comment]
hab ich gerade erledigt einfach den buttons in StateMachine sx={{m: 2 }} gegben

**Comment by JannikHoefener** [comment]
![image](https://user-images.githubusercontent.com/82703032/209689665-1370b7e2-52f3-40b3-8da1-65d1370af3b6.png)
Margin eingefügt; oder soll der Button zentriert werden? @Hyper1701
