### ISSUE TITLE
Grid aufbrechen bei mobiler Darstellung

### ISSUE THREAD

**Issue by HSoeren** [se-ws22-ihnn/ihnn#39]
<img width="533" alt="Grid bricht nicht auf" src="https://user-images.githubusercontent.com/25493517/209465833-9fd128c0-e49f-4579-a181-95008d02eeca.png">

beim Unterschreiten einer gewissen Bildschirmgröße sollte das Grid automatisch aufgegeben werden, damit es besser dargestellt wird.

**Comment by HSoeren** [comment]
https://mui.com/material-ui/customization/breakpoints/

**Comment by HSoeren** [comment]
https://blog.logrocket.com/guide-mui-grid-system/
unter Fluid

**Comment by HSoeren** [comment]
lediglich die `src/Pages/FinalScores.tsx` passt noch nicht ganz, da hier auch keine korrekten Boxen verteilt wurden @JannikHoefener

**Comment by HSoeren** [comment]
> <img alt="Grid bricht nicht auf" width="533" src="https://user-images.githubusercontent.com/25493517/209465833-9fd128c0-e49f-4579-a181-95008d02eeca.png">
> 
> beim Unterschreiten einer gewissen Bildschirmgröße sollte das Grid automatisch aufgegeben werden, damit es besser dargestellt wird.

todo Sören: Texte von den Symbolen entfernen, wenn in mobiler Darstellung!

**Comment by HSoeren** [comment]
Mittlerweile teilt sich alles korrekt auf, nur die Navbar bleibt mir dem Text...
![image](https://user-images.githubusercontent.com/25493517/209696758-21a4be09-9f7f-4ce7-a08b-a6f2819c14c2.png)

**Comment by HSoeren** [comment]
@Hyper1701 passt das Design so für dich oder muss hier noch etwas gemacht werden?

**Comment by Hyper1701** [comment]
@HSoeren Mobile apps haben nochmal andere anforderungen bezüglich der Visuallität gegensätzlich zu Desktops, bin aber selbst mit diesen nicht super vertraut mein aber das es soweit es schon echt solide aussieht. Ich würd aber selbst noch die tage schauen ob ich noch den unteren teil der website interessanter gestallten kann. Vieleicht mit unserem Logo im Hintergrund.

**Comment by HSoeren** [comment]
Ich würde das Issue damit schließen. Weitere Verschönerungen können dann gerne als neues Issue getrackt werden.
