### ISSUE TITLE
Datenbank Schnittstelle (REST API)  

### ISSUE THREAD

**Issue by JannikHoefener** [se-ws22-ihnn/ihnn#41]
MongoDB wird zeitlich nichts mehr! @HSoeren wir müssen uns um eine API kümmern!

**Comment by HSoeren** [comment]
https://github.com/se-ws22-ihnn/ihnn-api

**Comment by HSoeren** [comment]
Ist gelöst, läuft alles und daher nun alles zu Main übergeben
