### ISSUE TITLE
Hintergrundbild/Styling überarbeitet

### ISSUE THREAD

**Issue by Hyper1701** [se-ws22-ihnn/ihnn#45]
#12 #24 
Logo dem Hintergrund hinzugefügt und Light-und Dark Theme Noise erstellt.

**Comment by HSoeren** [comment]
![chrome-P0op72xzql](https://user-images.githubusercontent.com/25493517/210276764-9259d23f-e8b0-47af-a202-d9e7e10fdbe8.png)

die verwendung von Table, insb mit absoluten Abmessungen skaliert nicht mehr und bricht das Design...

**Comment by HSoeren** [comment]
![image](https://user-images.githubusercontent.com/25493517/210276887-75d6117a-e520-4981-aec6-0993ded8d48e.png)

`<Block sx={{ backgroundColor: '#eeeeee' }}>`

regelt jetzt die Darstellung der Frage an sich.

**Comment by HSoeren** [comment]
6859c7ddeaaab65abc2a997fb70b01284f939af0 kümmert sich um folgendes Problem: 
![chrome-0Gca6A9qI1](https://user-images.githubusercontent.com/25493517/210283306-31b4bc0e-a6ac-474b-ac54-4a789743280b.png)

**Comment by HSoeren** [comment]
Grundsätzlich erledigt. Neue Wünsche als Extra Commit machen
