### ISSUE TITLE
handle Key Error

### ISSUE THREAD

**Issue by JannikHoefener** [se-ws22-ihnn/ihnn#46]
![image](https://user-images.githubusercontent.com/82703032/210063737-5ebe9505-091a-4c6c-b972-1adf0dee5ae6.png)
![image](https://user-images.githubusercontent.com/82703032/210063770-16dc49bc-734c-419b-bf52-dcbaf2301e55.png)

**Comment by HSoeren** [comment]
wurde in Commit 4ae709d8a112280e1c2b19f6d2fd33b10f746365 behoben.
