### ISSUE TITLE
NavBar Name ausblenden wenn mobile ansicht

### ISSUE THREAD

**Issue by HSoeren** [se-ws22-ihnn/ihnn#47]
Was haltet ihr von der Idee? 

<img width="416" alt="vorher" src="https://user-images.githubusercontent.com/25493517/210172696-877e3272-7b75-431d-aac1-1574597e8dbe.png">

<img width="416" alt="nachher" src="https://user-images.githubusercontent.com/25493517/210172714-2e0ee839-191b-4099-9705-7ea615da994b.png">

Ist jetzt nur interaktiv im Browser getestet, aber ein Vorschlag.

**Comment by HSoeren** [comment]
Viel unterschied macht es allerdings auch nicht, selbst die margin von dem Theme Schalter zu entfernen holt den Umbruch aus "Frage hinzufügen" nicht raus. 

einziges wäre #15 - falls es nicht mehr mit Funktion ausgerüstet wird, den schalter komplett zu entfernen und das Feature auf Nice To Have zu verlegen.

<img width="416" alt="vorschlag" src="https://user-images.githubusercontent.com/25493517/210172832-2b647944-9a12-4dce-acc3-2615dfb07c5d.png">

**Comment by Hyper1701** [comment]
Sieht gut aus und mich persönlich stört der Umbruch auch nicht.
Aber man kann da den Theme Button ja wie du meinst auch entfernen wenn er momentan nix tut. Wir müssen uns nur natürlich daran erinnern ihn später wieder hinzuzufügen.

**Comment by HSoeren** [comment]
Der ThemeSelector wird nun erstmal nicht mehr angezeigt, siehe #15.

Umbruch ist dennoch dabei, aber wenn das nicht stört, isses ja ok.
![image](https://user-images.githubusercontent.com/25493517/210283709-e76bc6e5-4f1c-4f8e-abf4-a7033e72ad60.png)

(falls doch, Issue wieder öffnen)
